# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

jobs:
- job: List_Helix_Jobs
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    displayName: Invoke Helix REST API
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'Helix.Net API'
      method: 'GET'
      urlSuffix: api/jobs?Creator=GitHub&count=20&api-version=2019-06-17
      waitForCompletion: true
      header: '{}'
