# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

jobs:
- job: List_Helix_WorkItems
  pool: server
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'Helix.Net API'
      method: 'GET'
      urlSuffix: api/jobs/458c9301-eae6-4d8d-8abd-d5afddf177fd/workitems?api-version=2019-06-17
      waitForCompletion: false
      header: '{}'
