# Build on windows desktop
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 40

  variables:
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

  steps:
    - template: checkout-windows-task.yml

    - task: Cache@2
      inputs:
        key: 'nuget | "$(Agent.OS)" | eng/Versions.props,!**/bin/**'
        restoreKeys: |
          nuget | "$(Agent.OS)"
        path: $(NUGET_PACKAGES)
      displayName: Cache NuGet packages

    - task: PowerShell@2
      displayName: Restore
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -restore -binaryLog

    - task: PowerShell@2 
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -build -publish -binaryLog -skipDocumentation "/p:ROSLYNUSEHARDLINKS=true"

    - task: PowerShell@2 
      displayName: Prepare Unit Tests
      inputs:
        filePath: eng/prepare-tests.ps1
        arguments: -configuration ${{ parameters.configuration }}

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)\artifacts\testPayload'
        artifactName: ${{ parameters.testArtifactName }}

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}

