# Build on windows desktop
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: queueName
  type: string
  default: ''
- name: vmImageName
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  pool:
    ${{ if ne(parameters.queueName, '') }}:
      name: NetCorePublic-Pool
      queue: ${{ parameters.queueName }}

    ${{ if ne(parameters.vmImageName, '') }}:
      vmImage: ${{ parameters.vmImageName }}
  timeoutInMinutes: 40

  steps:
    - pwsh: |
        New-Item -Path 'D:\h\w\roslyn\' -ItemType Directory
        Set-Location 'D:\h\w\roslyn\'
      displayName: Set Working Directory

    - template: checkout-windows-task.yml

    - task: PowerShell@2
      displayName: Restore
      inputs:
        workingDirectory: 'D:\h\w\roslyn\'
        filePath: D:/h/w/roslyn/eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -restore -binaryLog

    - task: PowerShell@2 
      displayName: Build
      inputs:
        workingDirectory: 'D:\h\w\roslyn\'
        filePath: D:/h/w/roslyn/eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -build -publish -binaryLog -skipDocumentation

    - task: PowerShell@2 
      displayName: Prepare Unit Tests
      inputs:
        workingDirectory: 'D:\h\w\roslyn\'
        filePath: D:/h/w/roslyn/eng/prepare-tests.ps1
        arguments: -configuration ${{ parameters.configuration }}

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        workingDirectory: 'D:\h\w\roslyn\'
        targetPath: 'D:\h\w\roslyn\artifacts\testPayload'
        artifactName: ${{ parameters.testArtifactName }}

    - task: PublishPipelineArtifact@1
      displayName: Publish Prepare Tests Trace
      inputs:
        workingDirectory: 'D:\h\w\roslyn\'
        targetPath: 'D:\h\w\roslyn\trace.speedscope.json'
        artifactName: trace.speedscope.windows.${{ parameters.configuration }}.json

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}

