parameters:
- name: testRunName
  type: string
  default: ''
- name: jobName
  type: string
  default: ''
- name: buildJobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: testArguments
  type: string
  default: ''
- name: queueName
  type: string
  default: ''
- name: vmImageName
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.buildJobName }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 40
  steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: Download Test Payload
      inputs:
        artifact: ${{ parameters.testArtifactName }}
        path: '$(Build.SourcesDirectory)'

    - task: ShellScript@2
      displayName: Rehydrate Unit Tests Environment
      inputs:
        scriptPath: ./artifacts/bin/RunTests/${{ parameters.configuration }}/netcoreapp3.1/rehydrate.sh
      env:
        HELIX_CORRELATION_PAYLOAD: '$(Build.SourcesDirectory)/.duplicate'

    # Work around for files not maintaining permissions after pipeline download
    # https://github.com/microsoft/azure-pipelines-tasks/issues/6364
    - bash: |
        find artifacts/bin -name ilasm | xargs chmod 755
        chmod 755 eng/build.sh
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: Fix executable permissions in pipeline artifact

    - script: ./eng/build.sh --ci --configuration ${{ parameters.configuration }} ${{ parameters.testArguments }}
      displayName: Test
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - task: PublishTestResults@2
      displayName: Publish xUnit Test Results
      inputs:
        testRunner: XUnit
        testResultsFiles: '$(Build.SourcesDirectory)/artifacts/TestResults/${{ parameters.configuration }}/*.xml'
        mergeTestResults: true
        testRunTitle: ${{ parameters.testRunName }}
      condition: false

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
